language: cpp

os: linux
compiler: gcc

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

install:
  - sudo apt-get install mpich libmpich-dev
  - sudo apt-get install libpthread-stubs0-dev

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --config release -- -j4
  - cd Release
  - mpiexec -n 4 ./sum_of_vector 50
  - mpiexec -n 4 ./matrixvector 50 50
  - mpiexec -n 5 ./matrixmult -size 2
  - mpiexec -n 5 ./locks_simple_sample 50
  - mpiexec -n 5 ./parallel_reduce_sum_of_vector 50
  - mpiexec -n 5 ./sum_of_vector_struct 50
  - mpiexec -n 5 ./dijkstra -v 500
  - mpiexec -n 5 ./matrixmult_queue -size 100 -d 4
